const GET_HOTELS = 'GET_HOTELS';
const GET_DATE_RANGE = 'GET_DATE_RANGE';
const SELECT_HOTEL = 'SELECT_HOTEL';
const SELECT_DATE_RANGE = 'SELECT_DATE_RANGE';

export {
  GET_HOTELS,
  GET_DATE_RANGE,
  SELECT_HOTEL,
  SELECT_DATE_RANGE,
};
