const GET_HOTELS_SUCCESS = 'GET_HOTELS_SUCCESS';
const GET_ROOM_TYPES = 'GET_ROOM_TYPES';
const GET_DATE_RANGES_SUCCESS = 'GET_DATE_RANGES_SUCCESS';
const SELECT_HOTEL = 'SELECT_HOTEL';
const SELECT_DATE_RANGE = 'SELECT_DATE_RANGE';
const SELECT_ROOM_TYPE = 'SELECT_ROOM_TYPE';
const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

export {
  GET_HOTELS_SUCCESS,
  GET_ROOM_TYPES,
  GET_DATE_RANGES_SUCCESS,
  SELECT_HOTEL,
  SELECT_DATE_RANGE,
  SELECT_ROOM_TYPE,
  SEARCH_SUCCESS,
};
